# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-12 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('SID', models.AutoField(primary_key=True, serialize=False)),
                ('SName', models.CharField(max_length=100)),
                ('Language', models.CharField(max_length=100)),
                ('Composer', models.CharField(max_length=100)),
                ('Tonality', models.CharField(max_length=100)),
                ('Verion', models.CharField(max_length=100)),
            ],
        ),
    ]
