# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-12 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('PID', models.AutoField(primary_key=True, serialize=False)),
                ('PName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('SID', models.AutoField(primary_key=True, serialize=False)),
                ('SName', models.CharField(max_length=100)),
            ],
        ),
    ]
