# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-12 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer', '0002_performance_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumentalist',
            fields=[
                ('IID', models.AutoField(primary_key=True, serialize=False)),
                ('IName', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Instrument', models.CharField(max_length=100)),
                ('Music_Training', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vocalist',
            fields=[
                ('VID', models.AutoField(primary_key=True, serialize=False)),
                ('VName', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Vocal_Range', models.CharField(max_length=100)),
                ('Vocal_Type', models.CharField(max_length=100)),
                ('Language', models.CharField(max_length=100)),
                ('Music_Training', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='performance',
            name='Company',
            field=models.CharField(default='Company', max_length=100),
        ),
        migrations.AddField(
            model_name='performance',
            name='Date',
            field=models.CharField(default='2019/01/01', max_length=100),
        ),
        migrations.AddField(
            model_name='performance',
            name='Equipment',
            field=models.CharField(default='Equipment', max_length=100),
        ),
        migrations.AddField(
            model_name='performance',
            name='Venue',
            field=models.CharField(default='Venue', max_length=100),
        ),
    ]
